Repository NYU-DevOps-Fall19-Payments-Team/payments, pull requests merged in 2019-12, with the labels that each got.

#144 Writeme
  README.md
Labels: documentation

#145 Better ui
  README.md
  features/payments.feature
  features/steps/payment_steps.py
  service/static/css/footable.bootstrap.css
  service/static/css/footable.bootstrap.min.css
  service/static/css/style.css
  service/static/index.html
  service/static/js/payment.js
Labels: enhancement

#146 Fix Swagger Docs not showing models
  service/service.py
Labels: bug
