Repository NYU-DevOps-Fall19-Payments-Team/payments, pull requests merged in 2019-10, with the labels that each got.

#44 Corrected functions and docstrings to say "payment[s]" instead of "pet[s]."
  service/models.py
  service/service.py
Labels: documentation

#48 Renamed tests/_init_.py to tests/__init__.py
  tests/__init__.py
Labels: technical debt

#51 stateful action created
  service/service.py
  tests/test_payments.py
  tests/test_server.py
Labels: enhancement

#61 Include travis and codecov
  .gitignore
  .travis.yml
  README.md
Labels: documentation, technical debt
